apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.name }}
  labels:
    helm.sh/release: {{ .Release.Name }}
spec:
  role: {{ required "Missing IAM node role" .Values.nodeClass.role }}
  amiSelectorTerms:
    # family@version
    - alias: al2023@latest
  # cannot pass object directly from values, pasted as a map reference
  {{- range $tag, $val := required "Missing selector tags" .Values.nodeClass.selectorTags }}
  subnetSelectorTerms:
    - tags:
        {{ $tag }}: {{ $val | quote }}
  securityGroupSelectorTerms:
    - tags:
        {{ $tag }}: {{ $val | quote }}
  {{- end }}

